name: Edit About page (sections)
description: Update predefined sections of about.markdown without touching HTML
labels: [content-edit, about]
body:
  - type: textarea
    id: about_intro
    attributes:
      label: Intro paragraph
      description: Replaces content inside <!-- CMS:section id=about_intro -->
    validations:
      required: false
  - type: textarea
    id: about_what_it_does
    attributes:
      label: What does it do?
      description: Replaces content inside <!-- CMS:section id=about_what_it_does -->
    validations:
      required: false
  - type: textarea
    id: about_scope
    attributes:
      label: Scope
      description: Replaces content inside <!-- CMS:section id=about_scope -->
    validations:
      required: false
  - type: textarea
    id: about_audience
    attributes:
      label: Target audience
      description: Replaces content inside <!-- CMS:section id=about_audience -->
    validations:
      required: false
  - type: textarea
    id: about_outcomes
    attributes:
      label: Outcomes
      description: Replaces content inside <!-- CMS:section id=about_outcomes -->
    validations:
      required: false
  - type: textarea
    id: about_getting_started
    attributes:
      label: Getting started
      description: Replaces content inside <!-- CMS:section id=about_getting_started -->
    validations:
      required: false
  - type: textarea
    id: about_contribute
    attributes:
      label: Contribute
      description: Replaces content inside <!-- CMS:section id=about_contribute -->
    validations:
      required: false

