name: "Edit content (auto prefill)"
description: "Edit an existing file from the repository"
title: "Edit request: "
labels: ["content-edit"]
body:
  - type: input
    id: file
    attributes:
      label: "Which file do you want to edit?"
      description: "Example: about.markdown, application.markdown, etc."
      placeholder: "about.markdown"
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: "Additional comment"
      description: "Anything else you'd like to note"
      placeholder: "Optional comment..."
    validations:
      required: false

