name: Edit Applications sections to PR

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-pr:
    if: contains(github.event.issue.labels.*.name, 'applications')
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Parse issue form
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            function extract(label){
              const re = new RegExp(`###\\s+${label}\\n([\\s\\S]*?)(?=\\n###|$)`, 'i');
              const m = body.match(re);
              return m ? m[1].trim() : '';
            }
            const out = {
              applications_intro: extract('Intro paragraph'),
              applications_reading_intro: extract('Reading intro paragraph')
            };
            core.setOutput('json', JSON.stringify(out));

      - name: Update application.markdown sections
        run: |
          python3 - << 'PY'
  import json, re
  data = json.loads('${{ steps.parse.outputs.json }}')
  path = 'application.markdown'
  src = open(path,'r',encoding='utf-8').read()
  def replace_section(text, section_id, new_html):
      if not new_html.strip():
          return text
      pattern = re.compile(r'(<!--\s*CMS:section\s+id=' + re.escape(section_id) + r'\s*-->)([\s\S]*?)(<!--\s*/CMS:section\s*-->)', re.M)
      return pattern.sub(lambda m: m.group(1) + '\n' + new_html.strip() + '\n' + m.group(3), text)
  for key in ['applications_intro','applications_reading_intro']:
      src = replace_section(src, key, data.get(key,'') )
  open(path,'w',encoding='utf-8').write(src)
PY

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Edit Applications sections via issue #${{ github.event.issue.number }}"
          title: "Edit Applications sections"
          body: |
            Auto-generated from issue #${{ github.event.issue.number }}.
          branch: "content/applications-issue-${{ github.event.issue.number }}"
          delete-branch: true


